### PR TITLE
Resolved issue #13, #14 and #15

### PR DESCRIPTION
**Pull request by Mahak008**
You can watch the demo here - 
https://mahak008.github.io/PortfolioCreations/

image

### CODE REVIEW

**Comment by ayushichoudhary-19** [comment]
@Mahak008, thank you for your PR. I've noticed a few points for improvement:

1. The colors used don't align with the website's color palette. Please ensure consistency with the established color scheme.

2. Consider relocating the "Download CV" button. Having it fixed on the screen at all times might affect the overall layout. Perhaps, placing it in the navbar or header section could be a better fit.

3. Regarding the loader, it doesn't quite align with the design aesthetics, and the loading timespan is too short for a thorough check. Let's adjust it to match the overall design and ensure a more user-friendly loading experience.

Looking forward to your updates. Thanks!

**Review by Nitya-Pasrija — COMMENTED** [review]
Furthermore, I strongly suggest creating 3 different PRs to resolve the 3 issues, instead of one single PR. Do look into branching. Feel free to contact us if you are confused :)

**Comment by Nitya-Pasrija** [comment]
Also, there are conflicting files as well. Please look into it.

**Comment by Mahak008** [comment]
> @Mahak008, thank you for your PR. I've noticed a few points for improvement:
> 
> 1. The colors used don't align with the website's color palette. Please ensure consistency with the established color scheme.
> 2. Consider relocating the "Download CV" button. Having it fixed on the screen at all times might affect the overall layout. Perhaps, placing it in the navbar or header section could be a better fit.
> 3. Regarding the loader, it doesn't quite align with the design aesthetics, and the loading timespan is too short for a thorough check. Let's adjust it to match the overall design and ensure a more user-friendly loading experience.
> 
> Looking forward to your updates. Thanks!

Ok I will make the required changes. Can you please close this PR. Iwill create separate PR for all the issues.

**Comment by ayushichoudhary-19** [comment]
Sure, @Mahak008! Feel free to make the necessary changes. I'll go ahead and close this pull request for now. Looking forward to seeing those separate pull requests for each issue.

**Pull request closed without merging**
