### PR TITLE
Changed the layout of Project section and made it responsive. #10

### PR DESCRIPTION
**Pull request by Riddhi050803**
Changed the layout, made it responsive and changed the font for the section as well.
DESKTOP SCREEN

https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/122264483/945d0249-1cc3-4134-9713-e71467234f5a

TABLET SCREEN
Screenshot 2024-01-02 104855

MOBILE SCREEN
Screenshot 2024-01-02 105026

### CODE REVIEW

**Review by Nitya-Pasrija — COMMENTED** [review]
Perfection! Advancing through the open source world!🎊🎊 :) Please be patient while our maintainers and reviewers check the code.

**Comment by Riddhi050803** [comment]
kindly review it @ayushichoudhary-19

**Comment by ayushichoudhary-19** [comment]
@Riddhi050803  This appears well done, but could we make a slight modification? Currently, all the projects are listed in a single card-like box, but I think it might be better if we create a separate card for each project. Also, I do not see the relevance of adding project logos, so let's skip those for now. Thanks for your work!

**Comment by Riddhi050803** [comment]
@ayushichoudhary-19 Thankyou for your recommendation. I have made certain modifications as per your suggestion. You may review it now



https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/122264483/38836a24-d778-4510-8e35-5f643c664476

**Comment by ayushichoudhary-19** [comment]
Awesome work, @Riddhi050803! Merging it right away!✨
(Closes issue #10)

**Pull request merged**
