### PR TITLE
Added certification section

### PR DESCRIPTION
**Pull request by namitabagri**
- Added certification section
- Added buttons with certification links
- added image to the certification section - to make it aesthetic
- added certification section link to navbar
The final look  of the certification section is: 
image

Also , the additional link to certification in the navbar looks like this
image

Please merge my PR :)

### CODE REVIEW

**Review by Nitya-Pasrija — COMMENTED** [review]
Perfection! Advancing through the open source world!🎊🎊 :) Please be patient while our maintainers and reviewers check the code.

**Comment by Nitya-Pasrija** [comment]
Why are there so many commits via one PR?

**Comment by namitabagri** [comment]
> Why are there so many commits via one PR? 

Hi,
Is there a max commit criteria?

( I am a ML developer - not well versed in web dev ( beginner), so I made commits at every step so that of there's a mistake I could go back to the previous step)

Sorry for the inconvenience,  will keep a limited number of commits in the next PRs.

**Comment by ayushichoudhary-19** [comment]
@namita0210, thank you for your work on the certification section! I noticed that the current color palette doesn't quite align with the overall design aesthetics of the website. Could you please modify the colors to ensure consistency?

Additionally, the design appears somewhat distinctive, resembling more of a banner. To fix this, I suggest increasing the height of the section and aligning the buttons – perhaps having two buttons in each row. This would improve the visual balance. 

I look forward to seeing the updated design. If you have any questions or need further clarification, feel free to ask. Thanks!

**Comment by namitabagri** [comment]
> @namita0210, thank you for your work on the certification section! I noticed that the current color palette doesn't quite align with the overall design aesthetics of the website. Could you please modify the colors to ensure consistency?
> 
> Additionally, the design appears somewhat distinctive, resembling more of a banner. To fix this, I suggest increasing the height of the section and aligning the buttons – perhaps having two buttons in each row. This would improve the visual balance.
> 
> I look forward to seeing the updated design. If you have any questions or need further clarification, feel free to ask. Thanks!

Sure @ayushichoudhary-19 
Will make the changes as recommended in a short while. Thanks for the feedback.

**Comment by ayushichoudhary-19** [comment]
Hey @namita0210, quick reminder!

Before committing any more changes, please take a moment to `git pull` the latest changes from the repository to ensure your work is in sync. This helps prevent any conflicts or merge issues down the line.

**Comment by namitabagri** [comment]
Sure

**Comment by ayushichoudhary-19** [comment]
@namita0210, it appears that the requested changes haven't been made for quite some time, and in the interim, another contributor has timely created a certificate section through a different PR. Regrettably, we will need to close this Pull Request if the changes aren't made by midnight tonight.

We sincerely encourage you to make the necessary adjustments before the deadline!

Additionally, please be aware that your PR currently has merge conflicts. Ensure you run `git pull` to fetch the latest changes from the repository before updating your PR with new commits.

**Comment by namitabagri** [comment]
Yes, I am working on it.

**Pull request closed without merging**
