### PR TITLE
Faq section

### PR DESCRIPTION
**Pull request by aarushisingh2004**
#6 As per the issue assigned to me , I had to add the FAQ section , which I have completed , please review 
 The section looks like:-

faq1

faq2

### CODE REVIEW

**Comment by aarushisingh2004** [comment]
I have added the FAQ section , #6 issue  that was assigned to me , please review the pull request  @i-am-SnehaChauhan

**Review by Nitya-Pasrija — CHANGES_REQUESTED** [review]
Hey @aarushisingh2004 
Good work, but there are conflicts in a few files, kindly resolve it. 
Also would love it if you could round up the edges a little more

**Comment by Nitya-Pasrija** [comment]
Would suggest a git pull so that index.html and styles.html can be updated as it can be the cause of the conflict.

**Comment by aarushisingh2004** [comment]
image
 I have made the corners this much round , is it fine @Nitya-Pasrija di plz check

**Comment by aarushisingh2004** [comment]
di @Nitya-Pasrija  i made the pr again by making all suggested changes , please check, I made a new pr because I was not getting how to add changes in the same pr

**Pull request merged**
