### PR TITLE
responsive navbar

### PR DESCRIPTION
**Pull request by Akanksha-202**
Here's the preview:
https://jam.dev/c/60268249-5408-4e85-9c67-51d80714f475

### CODE REVIEW

**Review by Nitya-Pasrija — COMMENTED** [review]
Perfection! Advancing through the open source world!🎊🎊 :) Please be patient while our maintainers and reviewers check the code.

**Comment by ayushichoudhary-19** [comment]
👏 Awesome work @Akanksha-202 ! Merging your PR right away!

**Review by ayushichoudhary-19 — APPROVED** [review]

**Review by ayushichoudhary-19 — CHANGES_REQUESTED** [review]
Can we remove this extra padding at the bottom and align the design more closely with your initial proposal?

Current:
image


Expected:
image

**Comment by Akanksha-202** [comment]
Sure sure, I'll make the changes asap

**Comment by Akanksha-202** [comment]
image
Is it fine now? @ayushichoudhary-19

**Comment by ayushichoudhary-19** [comment]
Awesome work, @Akanksha-202 . This navbar is a great contribution to the project! 🥳

While it does cause some unintended changes in the education section (which will be addressed in another PR), please remember to git pull and synchronize with the latest repository changes before submitting future PRs to avoid unintended impacts on other sections.

Overall, your contribution is highly appreciated. Keep up the fantastic work!

**Pull request merged**
