### PR TITLE
Added Hover effect to testimonals-card

### PR DESCRIPTION
**Pull request by ShaikArshidBanu**
Added hover effects to testimonal cards and icons (emojis)  in the card.
solves  #61 
Please review the PR.

### CODE REVIEW

**Review by ayushichoudhary-19 — CHANGES_REQUESTED** [review]
On hover, the testimonial cards scale up, but there's an issue where the cards extend beyond the boundaries of the containing div. Please address this by adjusting the CSS to ensure that the scaled cards stay within the confines of the containing div.

**Comment by ShaikArshidBanu** [comment]
> On hover, the testimonial cards scale up, but there's an issue where the cards extend beyond the boundaries of the containing div. Please address this by adjusting the CSS to ensure that the scaled cards stay within the confines of the containing div.

Okay I'll do the necessary changes.

**Comment by ayushichoudhary-19** [comment]
@ShaikArshidBanu Are you working on the changes?

**Comment by ayushichoudhary-19** [comment]
@ShaikArshidBanu, make the requested changes at the earliest.

**Comment by ShaikArshidBanu** [comment]
> @ShaikArshidBanu, make the requested changes at the earliest.

@ayushichoudhary-19 I tried solving this issue but unable to fix it please unassign me this issue.

**Pull request closed without merging**
